### ISSUE TITLE
Inconsistent HTTP replying

### ISSUE THREAD

**Issue by fharding1** [Pigmice2733/scouting-backend#107]
Some functions are using `json.NewEncoder(w).Encode(asdf)`, some are using `w.Write(asdf)` when they all should be using `respond.JSON(w, asdf)`. Also, `http.Error` calls should *ONLY* be for stuff like 500's or 405's or something. If you want to tell the client an error, use a 200 and just reply with `respond.JSON(err)`. It will automatically make it `{"error": "this is the error"}`. It is also okay to use `w.WriteHeader` if you are conveying something like `StatusCreated` or some generic simple thing. If it's something like `couldn't get events` and you want to convey that to the frontend, use a 200 and respond.JSON.

**Comment by BrendanBurkhart** [comment]
Shouldn't an error status be returned for something like a 400, 404, 403, etc.?

**Comment by fharding1** [comment]
Yeah that's what I meant by "or something" lol. I just mean don't use like `http.Error(w, "failed to create team in alliance", http.StatusBadRequest)`. You really should just do `respond.JSON(w, err)` if you *really* want to convey that info.

**Comment by BrendanBurkhart** [comment]
Wouldn't a failure to execute the request require a status code of either 500 or 400 depending on whose at fault?

**Comment by calebeby** [comment]
Can't we return an error code and a response?

**Comment by fharding1** [comment]
Sure. But Brendan and I decided we're not returning specific errors anyways, just http errors.
