### ISSUE TITLE
Allow scouters to submit notes with reports

### ISSUE THREAD

**Issue by calebeby** [Pigmice2733/scouting-backend#178]
This also needs to be a frontend thing, we can open an issue once it is implemented here.

I suggest:

A `notes` field on `report` that is a string. When we are fetching a team at an event, return all the notes as an array, with each note including the match it came from and the reporter who submitted the note

**Comment by fharding1** [comment]
I feel like just concatenating the notes fields might be fine.

**Comment by calebeby** [comment]
I feel like having the notes attached to matches would be important so we can review video footage

**Comment by calebeby** [comment]
For example if a note said they were really good at defense we'd want to
know how

**Comment by fharding1** [comment]
The note should not just say "good at defense". The whole points of notes is concise snippets that can advise drive team and us when we are looking for alliance partners. We could always review the videos, that just seems like a waste of time.

**Comment by simonflyer11** [comment]
Have a view for both. Or at least be able to track them chronologically. It's important to be able to see how a team changes/addresses issues throughout competition

**Comment by calebeby** [comment]
Can you give me examples of things that would be in notes?
