### ISSUE TITLE
Use key as primary key

### ISSUE THREAD

**Issue by calebeby** [Pigmice2733/scouting-backend#2]
Why is the integer used as the primary key rather than the event key?

**Comment by BrendanBurkhart** [comment]
Could you elaborate? I assume you are talking about the `matches` table and the separate `id` and `eventID` columns, is that correct?

**Comment by calebeby** [comment]
Ya. I made the change locally and it worked. Is there a reason, or should I PR?

**Comment by BrendanBurkhart** [comment]
Which column did you delete? That shouldn't work, I need to improve the unit tests. The `id` is unique to each individual match, while `eventID` is not.

**Comment by calebeby** [comment]
Actually I mean events table

**Comment by BrendanBurkhart** [comment]
I don't understand, could you explain what you deleted?

**Comment by calebeby** [comment]
Now event is 

```go
type event struct {
	Key  string    `json:"key"`
	Name string    `json:"name"`
	Date time.Time `json:"date"`
}
```
and
```sql
CREATE TABLE IF NOT EXISTS events
(
	key TEXT PRIMARY KEY,
	name TEXT NOT NULL,
	date TEXT NOT NULL
)
```

**Comment by BrendanBurkhart** [comment]
Oh, I see. The `id` column is used to tie together an event with it's matches, it's necessary although not yet needed in the struct. Deleting it from the database creation query won't do anything unless you drop the table first, since it's already created. I'm a little confused though, what did you do in `getMatches` once the `event.id` was gone?

**Comment by calebeby** [comment]
```go
rows, err := db.Query("SELECT id, eventKey, winningAlliance FROM matches WHERE eventKey=?", e.Key)

```

**Comment by BrendanBurkhart** [comment]
So we could do that, but it is better to have our own primary key managed by the database. Performance shouldn't be too much of an issue, but we are using SQLite so it would also be better to use a number integer key for performance since we will have a decent amount of data being uploaded at once.

**Comment by calebeby** [comment]
When someone goes to a url, like `/event/2017orwil`, how are we to know which id that corresponds to?

**Comment by BrendanBurkhart** [comment]
Query by key if supplied with key, query by id if supplied with id. But no one should need to query by key, the correct thing to do is query using the `id` included in the json response, I think the API shouldn't even give out the TBA keys, those should only be used between the server and the tba API.

**Comment by calebeby** [comment]
Why though? We want our frontend URL scheme to match the TBA scheme, rather than using our arbitrary numbers. Is there really a performance penalty if we use strings as primary keys rather than integers?

**Comment by BrendanBurkhart** [comment]
Yeah, though I'm not sure how big it is. They tba key thing is honestly kind of bad practice, I'm a bit perplexed as to why they ever went that way. If we have a use case for the frontend querying tba directly then we should keep it as is - the backend sends the event key in the response. If not we can cut down the size of json by removing them.

**Comment by BrendanBurkhart** [comment]
Also I figured out the gzip thing, I don't need to send `Content-Encoding` in the header as gzip package does that automatically. When I was setting it manually the package would assume it was already compressed and leave it alone, then the browser would be left with unzipped json marked as gzipped.

**Comment by calebeby** [comment]
Oh, OK. Do you want me to push my code in a branch, or do you want to just do it yourself?

**Comment by BrendanBurkhart** [comment]
You should push of course.
