### ISSUE TITLE
Add more fields to match

### ISSUE THREAD

**Issue by calebeby** [Pigmice2733/scouting-backend#22]
```gql
{
  key
  predictedTime (if match hasn't happened yet)
  actualTime (if match happened)
  redAlliance {
    predictedScore or actualScore
    teams [
      {
        teamNumber
        predictedContributions
      }
    ]
  }
  blueAlliance {
    predictedScore or actualScore
    teams [
      {
        teamNumber
        predictedContributions
      }
    ]
  }
}
```

**Comment by BrendanBurkhart** [comment]
@calebeby You want both `actualTime` and `predictedTime` in the response?

**Comment by calebeby** [comment]
One or the other depending on whether the match has happened or not

**Comment by BrendanBurkhart** [comment]
With go's static typing that's a bit more difficult - not impossible but I would probably need to have two defined data structures, one with `actualTime` and one with `predictedTime`. Would it be reasonable to send both fields but keep one `null` and one filled in?

**Comment by calebeby** [comment]
Could we just have a single `time` field that is retrieved from the predicted time or from the actual time?

**Comment by BrendanBurkhart** [comment]
How do you want `predictedContributions` to be generated?

**Comment by calebeby** [comment]
For each field, if it's a boolean, it turns into a percentage, and if it's a number, it turns into an average

**Comment by BrendanBurkhart** [comment]
These should be based off of previous matches?

**Comment by calebeby** [comment]
Yes.

**Comment by BrendanBurkhart** [comment]
Do you still want just one field for time? Frank showed me a awesome feature that would make it fairly easy to separate it into predicted vs actual. Alliance scores as well, should they be combined or separated? Also the contributions, should there be one field, or a separate one once the results come in?

**Comment by GreenBeard** [comment]
@BrendanBurkhart Separate times seem better to me... For alliance scores separate again seems better (although a `totalScore` field would not be unappreciated). I am not sure about the contributions.

**Comment by BrendanBurkhart** [comment]
How would the `totalScore` field differ from the value of `predictedScore` or `actualScore`?

**Comment by calebeby** [comment]
I agree, separate times and scores would be useful.

**Comment by fharding1** [comment]
Just posting what I said to Brendan about how to implement this here for posterity.

Regarding actualTime and predictedTime, just for the future, it would be easy in Go to have an omitempty tag, and use a pointer to an int64 for time instead of just an int64. We do this because in Go everything has a zero value, so an int64 would just be 0 by default, and would be omitted if it was 0 (which we specified with omitempty) since 0 is the zero value, the problem being, if the time is actually zero. By using a pointer to an int64 we can make sure only a nil pointer will be omitted, not a valid pointer to 0. Example: https://play.golang.org/p/haS1aFS3pt (note that time doesn't really work on goplayground so rand doesn't really work)

**Comment by GreenBeard** [comment]
@BrendanBurkhart `totalScore` could be the total of all the `actualScore`s of the individual teams on the alliance. Unless I am misunderstanding and we are only tracking the overall scores of alliances, in which case never mind.

**Comment by BrendanBurkhart** [comment]
I see what you mean, all teams on the same alliance get the same score, it's a bit weird. So there is just going to be one score for the whole alliance in the response.

**Comment by GreenBeard** [comment]
@BrendanBurkhart Well, never mind then. I was thinking of how much each team contributed to the total alliance score, but I guess that would be overly complicated with how the competitions do scoring.

**Comment by BrendanBurkhart** [comment]
Oh.. yeah for now we can just use the contributions to see what each team did, crunching that into a score can be added later.
