### ISSUE TITLE
Use Postgres as DB

### ISSUE THREAD

**Issue by BrendanBurkhart** [Pigmice2733/scouting-backend#29]
SQLite is nice and portable but really doesn't support some of the functionality we need without using pretty hacky solutions. MySQL would be another option, but Postgres is the only DB currently supported by Heroku. We can get 10k rows of storage from Heroku for free which should be _way_ more than we will need for the testing server.

**Comment by BrendanBurkhart** [comment]
@calebeby

**Comment by calebeby** [comment]
Yeah, we could switch to postgres, but we aren't planning on staying on heroku, right?

**Comment by BrendanBurkhart** [comment]
Yeah, but there are other benefits. Golang's SQLite package has terrible error codes, so we're literally resorting to checking the error message. Postgres has much better error codes as well as other benefits. I don't think we need to switch right now, or even necessarily to Postgres but it would be good to ditch SQLite at some point. We will probably want to write a script to setup the database or something so we can keep it dead simple. Also there's no reason not to keep using Heroku as a testing environment, and have a better server setup as our 'production' environment.

**Comment by calebeby** [comment]
OK

**Comment by fharding1** [comment]
It's not just Go's SQLite package, but just SQLite in general that doesn't have descriptive error codes. The Go package lets us access raw errors, it's just SQLite will just give a generic error instead of a descriptive one for what we're doing.

**Comment by fharding1** [comment]
If we switch to postgres or use it at all, we should dockerize our application at least for testing, because postgres doesn't have an in-memory option. We can have a docker image for testing that spins up a docker instance and runs all the tests pretty easily. IDK how we'd integrate that with travis though, I don't know a ton about it.
