### ISSUE TITLE
Remove unneccesary writing of status code 200

### ISSUE THREAD

**Issue by fharding1** [Pigmice2733/scouting-backend#46]
Status code 200 will be written automatically if no other status codes are.

**Comment by BrendanBurkhart** [comment]
It wouldn’t be better to be explicit about exactly what status code is written to differentiate from having forgotten to write a 201 or something?

**Comment by fharding1** [comment]
It's implicit that a 200 is written if no other error code is written. If you need to write a 201, then just write that. If a handler doesn't end with an `http.WriteHeader` we can assume 200 is written, because otherwise the header would have been written in an error handling block and would have returned.
