### ISSUE TITLE
Add packages to govendor

### ISSUE THREAD

**Issue by fharding1** [Pigmice2733/scouting-backend#61]
We are not vendoring all of our packages I believe. We should! This is mostly my fault because I'm bad at using govendor :)

**Comment by BrendanBurkhart** [comment]
Maybe we can have travis use govendor rather than go get so we can tell if we forgot to add a new package.

**Comment by fharding1** [comment]
Good idea. Properly using govendor should also speed up test time since we won't have to fetch packages every time we want to test.
