### ISSUE TITLE
ON CONFLICT in UpdateEvents

### ISSUE THREAD

**Issue by fharding1** [Pigmice2733/scouting-backend#81]
Postgres is complaining about the `ON CONFLICT` clause in `UpdateEvents`. It hasn't happened up till now meaning it only happened when a conflict occured.

**Comment by BrendanBurkhart** [comment]
`ON CONFLICT` is a fairly new addition to PostgreSQL, it was only introduced in v9.5 I think. We're running v9.2 right now, so we need to either update or find another way to detect and handle the conflicts.

**Comment by BrendanBurkhart** [comment]
Awesome 🎉
